src/AppBundle/Entity/User.php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\User as BaseUser;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity as UniqueEntity;

/**
 * User
 *
 * @ORM\Table(name="user")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\UserRepository")
 * @UniqueEntity("email")
 * @ORM\HasLifecycleCallbacks()
 */
class User extends BaseUser
{
    const SEXE_MASCULIN = 'H';
    const SEXE_FEMININ = 'F';
    
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var Adresse
     * @ORM\OneToOne(targetEntity="AppBundle\Entity\Adresse")
     */
    private $adresse;

    /**
     * @var ArrayCollection
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Inscription", mappedBy="user")
     * @ORM\OrderBy({"dateTraitementDossier" = "DESC"})
     */
    private $inscriptions;

    /**
     * @var string
     *
     * @ORM\Column(name="prenom", type="string", length=255)
     */
    private $prenom;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=255)
     */
    private $nom;

    /**
     * @var string
     *
     * @ORM\Column(name="date_naissance", type="datetime")
     */
    private $dateNaissance;

    /**
     * @var string
     *
     * @ORM\Column(name="numero_federal", type="string", length=255)
     */
    private $numeroFederal;

    /**
     * @var string
     *
     * @ORM\Column(name="sexe", type="string", length=1)
     */
    private $sexe;

    /**
     * @var string
     *
     * @ORM\Column(name="demande_justificatif", type="boolean")
     */
    private $demandeJustificatif = false;

    /**
     * @var string
     *
     * @ORM\Column(name="telephone", type="string", length=255, nullable=true)
     */
    private $telephone;


    /**
     * @var Saison
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Saison")
     */
    private $saisonCourante;

    /**
     * Retourne l'inscription d'une année donnée
     * @param Saison $saison
     * @return Inscription|null
     */
    public function getInscriptionDeSaison(Saison $saison){
        $inscription = null;
        foreach($this->inscriptions as $i){
            if($i->getSaison()->getAnnee() === $saison->getAnnee()){
                $inscription = $i;
                break;
            }
        }
        return $inscription;
    }


    /**
     * Retourne l'année du certificat médical
     * @return null|int
     */
    public function getAnneeDerniereCertificatMedical()
    {
        $annee = null;
        /**@var \AppBundle\Entity\Inscription $derniereInscription * */
        $derniereInscription = $this->getDerniereInscription();
        if (false === is_null($derniereInscription)) {
            $annee = $derniereInscription->getSaison()->getAnnee();
        }
        return $annee;
    }

    /**
     * Retourne la dernière inscription
     * @return Inscription|null
     */
    public function getDerniereInscription()
    {
        $derniereInscription = $this->inscriptions->first();
        if (false === is_null($derniereInscription)) {
            return $derniereInscription;
        }
        return null;
    }

    /**
     * Retourne la première inscription
     * @return mixed|null
     */
    public function getPremiereInscription()
    {
        $premiereInscription = $this->inscriptions->last();
        if (false === is_null($premiereInscription)) {
            return $premiereInscription;
        }
        return null;
    }

    /**
     * Retourne la date de première inscription
     * @return \DateTime
     */
    public function getAnneePremiereInscription()
    {
        $date = null;
        /**@var \AppBundle\Entity\Inscription $derniereInscription * */
        $premiereInscription = $this->getPremiereInscription();
        if (false === is_null($premiereInscription)) {
            $date = $premiereInscription->getDateTraitementDossier();
        }
        return $date;
    }


    /**
     * Retourne si l'utilisateur a besoin d'un nouveau certificat médical
     * @return bool
     */
    public function necessiteNouveauCertificatMedical()
    {
        $necessite = true;
        $annee     = $this->getAnneeDerniereCertificatMedical();
        if (false === is_null($annee)) {
            $now       = new \DateTime();
            $necessite = ($now->format('Y') - $annee) > CertificatMedical::DUREE_VALIDITE_ANNEE_CERTIFICAT_MEDICAL;
        }
        return $necessite;
    }

    /**
     * Retourne la personne à contacter
     * @return null|PersonneContact
     */
    public function getPersonneContacte()
    {
        $personne    = null;
        $inscription = $this->getDerniereInscription();
        if (false === is_null($inscription)) {
            $personne = $inscription->getPersonneContact();
        }
        return $personne;
    }


    /**
     * Set prenom
     *
     * @param string $prenom
     *
     * @return User
     */
    public function setPrenom($prenom)
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * Get prenom
     *
     * @return string
     */
    public function getPrenom()
    {
        return $this->prenom;
    }

    /**
     * Set nom
     *
     * @param string $nom
     *
     * @return User
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set numeroFederal
     *
     * @param string $numeroFederal
     *
     * @return User
     */
    public function setNumeroFederal($numeroFederal)
    {
        $this->numeroFederal = $numeroFederal;

        return $this;
    }

    /**
     * Get numeroFederal
     *
     * @return string
     */
    public function getNumeroFederal()
    {
        return $this->numeroFederal;
    }

    /**
     * Set demandeJustificatif
     *
     * @param boolean $demandeJustificatif
     *
     * @return User
     */
    public function setDemandeJustificatif($demandeJustificatif)
    {
        $this->demandeJustificatif = $demandeJustificatif;

        return $this;
    }

    /**
     * Get demandeJustificatif
     *
     * @return boolean
     */
    public function getDemandeJustificatif()
    {
        return $this->demandeJustificatif;
    }

    /**
     * Set adresse
     *
     * @param \AppBundle\Entity\Adresse $adresse
     *
     * @return User
     */
    public function setAdresse(\AppBundle\Entity\Adresse $adresse = null)
    {
        $this->adresse = $adresse;

        return $this;
    }

    /**
     * Get adresse
     *
     * @return \AppBundle\Entity\Adresse
     */
    public function getAdresse()
    {
        return $this->adresse;
    }

    /**
     * Add inscription
     *
     * @param \AppBundle\Entity\Inscription $inscription
     *
     * @return User
     */
    public function addInscription(\AppBundle\Entity\Inscription $inscription)
    {
        $this->inscriptions[] = $inscription;

        return $this;
    }

    /**
     * Remove inscription
     *
     * @param \AppBundle\Entity\Inscription $inscription
     */
    public function removeInscription(\AppBundle\Entity\Inscription $inscription)
    {
        $this->inscriptions->removeElement($inscription);
    }

    /**
     * Get inscriptions
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getInscriptions()
    {
        return $this->inscriptions;
    }

    /**
     * Set telephone
     *
     * @param string $telephone
     *
     * @return User
     */
    public function setTelephone($telephone)
    {
        $this->telephone = $telephone;

        return $this;
    }

    /**
     * Get telephone
     *
     * @return string
     */
    public function getTelephone()
    {
        return $this->telephone;
    }

    /**
     * Set saisonCourante
     *
     * @param \AppBundle\Entity\Saison $saisonCourante
     *
     * @return User
     */
    public function setSaisonCourante(\AppBundle\Entity\Saison $saisonCourante = null)
    {
        $this->saisonCourante = $saisonCourante;

        return $this;
    }

    /**
     * Get saisonCourante
     *
     * @return \AppBundle\Entity\Saison
     */
    public function getSaisonCourante()
    {
        return $this->saisonCourante;
    }

    public function __construct()
    {
        parent::__construct();
        $this->inscriptions = new ArrayCollection();
    }

    /**
     * Set dateNaissance
     *
     * @param \DateTime $dateNaissance
     *
     * @return User
     */
    public function setDateNaissance($dateNaissance)
    {
        $this->dateNaissance = $dateNaissance;

        return $this;
    }

    /**
     * Get dateNaissance
     *
     * @return \DateTime
     */
    public function getDateNaissance()
    {
        return $this->dateNaissance;
    }

    /**
     * Set sexe
     *
     * @param string $sexe
     *
     * @return User
     */
    public function setSexe($sexe)
    {
        $this->sexe = $sexe;

        return $this;
    }

    /**
     * Get sexe
     *
     * @return string
     */
    public function getSexe()
    {
        return $this->sexe;
    }

    /**
     * @ORM\PrePersist
     */
    public function setFosValuePrePersist()
    {
        $this
            ->setUsername($this->getEmail())
            ->setEnabled(false)
            ->setPassword('');
    }

    /**
     * @ORM\PreUpdate()
     */
    public function setFosValuePreUpdate()
    {
        $this
            ->setUsername($this->getEmail())
        ->setUsernameCanonical($this->getEmail());
    }

    /**
     * Indique si l'utilisatuer a un email
     * @return int
     */
    public function hasEmail(){
        return strlen($this->getEmail())>0;
    }

    /**

src/AppBundle/Controller/AdherentController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Inscription;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;

/**
 * Class AdherentController
 * @package AppBundle\Controller
 * @Route("adherent")
 * @Security("has_role('ROLE_ADMIN')")
 */
class AdherentController extends Controller
{
    const FORM_RECHERCHE_TEXT = 'text';

    /**
     * @Route("/index")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexAction(Request $request)
    {

        $data = $this->getQueryListeAdherent($request);


        return $this->render('AppBundle:Adherent:index.html.twig', array(
            'liste_adherents' => $data['liste_adherent'],
            'form'            => $data['form']->createView()
        ));
    }

    /**
     * @Route("/edit")
     */
    public function editAction()
    {
        return $this->render('AppBundle:Adherent:edit.html.twig', array(// ...
        ));
    }


    /**
     * Crée le formulaire de recherche
     * @return \Symfony\Component\Form\Form
     */
    protected function createFormRecherche()
    {
        $listeTypeCours = array('-' => null);
        foreach (Inscription::LISTE_TYPE_COURS as $typeCours) {
            $listeTypeCours[ucfirst($typeCours)] = $typeCours;
        }
        $listeTypeAdhesion = array('-' => null);
        foreach (Inscription::LISTE_TYPE_ADHESION as $typeAdhesion) {
            $listeTypeAdhesion[ucfirst($typeAdhesion)] = $typeAdhesion;
        }
        return $this->createFormBuilder()
            ->add('text', TextType::class, array(
                'required' => false,
                'attr'     => array(
                    'placeholder' => 'Recherche sur prénom / nom'
                )
            ))
            ->add('typeCours', ChoiceType::class, array(
                'choices' => $listeTypeCours,
                'label'   => 'Type de cours'
            ))
            ->add('typeAdhesion', ChoiceType::class, array(
                'choices' => $listeTypeAdhesion,
                'label'   => "Type d'adhésion"
            ))
            ->getForm();
    }

    /**
     * @param Request $request
     * @return array
     */
    protected function getQueryListeAdherent(Request $request)
    {
        $formRecherche = $this->createFormRecherche()->handleRequest($request);
        $listeFiltres  = array();
        if ($formRecherche->isSubmitted() && $formRecherche->isValid()) {
            $listeFiltres = $formRecherche->getData();
        }

        $listeAdherents = $this->get('knp_paginator')->paginate(
            $this->getDoctrine()->getRepository('AppBundle:User')->getQueryListeUser($this->getUser()->getSaisonCourante(), $listeFiltres),
            1,
            100,
            array('defaultSortFieldName' => 'u.prenom', 'defaultSortDirection' => 'asc')
        );

        return array(
            'form'           => $formRecherche,
            'liste_adherent' => $listeAdherents,
        );
    }


    /**
     * @Route("/recherche",
     * options={"expose"=true}
     *     )
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function rechercheAction(Request $request)
    {
        $data = $this->getQueryListeAdherent($request);

        return $this->render('@App/Adherent/Block/liste_adherents.html.twig', array(
            'liste_adherents' => $data['liste_adherent'],
        ));
    }

}

src/AppBundle/Resources/views/Adherent/Block/liste_adherents.html.twig
{% import "macro/general.html.twig" as generalMacro %}
<div>
    Nombre d'adhérents trouvés : {{ liste_adherents|length }}
</div>
<table class="table table-striped table-responsive fe_liste d-none d-sm-block">
    <thead>
    <tr>
        <th class="col-sm-1 {{ generalMacro.gereTri(liste_adherents, 'u.prenom') }}">
            {{ knp_pagination_sortable(liste_adherents, 'Prénom', 'u.prenom') }}
        </th>
        <th class="col-sm-1 {{ generalMacro.gereTri(liste_adherents, 'u.nom') }}">
            {{ knp_pagination_sortable(liste_adherents, 'Nom', 'u.nom') }}
        </th>
        <th class="col-sm-1">
            Première inscription
        </th>
        <th class="col-sm-1">
            Date de validation
        </th>
        <th class="col-sm-1">
            Type de cours
        </th>
        <th class="col-sm-1">
            Type d'adhésion
        </th>
        <th class="col-sm-1">
            Date du dernier certificat médical
        </th>
        <th class="col-sm-2">
            Email
        </th>
        <th class="col-sm-2">
            Téléphone
        </th>
        <th class="col-sm-1">&nbsp;</th>
    </tr>
    </thead>
    <tbody>
    {% for adherent in liste_adherents %}
        {% set inscription = adherent.inscriptionDeSaison(get_saison_courante()) %}
        <tr data-id="{{ adherent.id }}">
            <td>
                {{ adherent.prenom }}
            </td>
            <td>
                {{ adherent.nom }}
            </td>
            <td>
                {{ adherent.premiereInscription.saison.annee }}
            </td>
            <td>
                {% if inscription.dateTraitementDossier is not null %}
                    {{ inscription.dateTraitementDossier|date('d/m/Y') }}
                {% else %}
                    -
                {% endif %}
            </td>
            <td>
                {{ get_label_type_cours(adherent.inscriptionDeSaison(get_saison_courante()).typeCours) }}
            </td>
            <td>
                {{ get_label_type_adhesion(adherent.inscriptionDeSaison(get_saison_courante()).typeAdhesion) }}
            </td>
            <td>
                {{ adherent.anneeDerniereCertificatMedical }}
            </td>
            <td>
                <a href="mailto:{{ adherent.email }}"> {{ adherent.email }}</a>
            </td>
            <td>
                <a href="tel: {{ adherent.telephone }}">  {{ adherent.telephone }}</a>
            </td>
            <td>
                <a class="fa fa-hand-o-right" aria-hidden="true"
                   title="Editer {{ adherent.prenom }} {{ adherent.nom }}"
                   href="{{ path('app_adherent_edit', {'id': inscription.id}) }}"></a>
                {% if adherent.hasEmail %}
                    <a class="fa fa-envelope-open-o " aria-hidden="true"
                       title="Envoyer un email à  {{ adherent.prenom }} {{ adherent.nom }}"
                       href="mailto: {{ adherent.email }}"></a>
                {% endif %}
                {% if adherent.hasTelephone %}
                    <a class="fa fa-phone" aria-hidden="true"
                       title="Téléphoner à  {{ adherent.prenom }} {{ adherent.nom }}"
                       href="tel: {{ adherent.telephone }}"></a>
                {% endif %}
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>


<table class="table table-striped table-responsive fe_liste d-sm-block d-md-none d-lg-none d-xl-none">
    <tbody>
    {% for adherent in liste_adherents %}
        {% set inscription = adherent.inscriptionDeSaison(get_saison_courante()) %}
        <tr data-id="{{ adherent.id }}">
            <td>
                {{ adherent.prenom }} {{ adherent.nom }}
                <a class="fa fa-hand-o-right" aria-hidden="true"
                   title="Editer {{ adherent.prenom }} {{ adherent.nom }}"
                   href="{{ path('app_adherent_edit', {'id': inscription.id}) }}"></a>
                {% if adherent.hasEmail %}
                    <a class="fa fa-envelope-open-o " aria-hidden="true"
                       title="Envoyer un email à  {{ adherent.prenom }} {{ adherent.nom }}"
                       href="mailto: {{ adherent.email }}"></a>
                {% endif %}
                {% if adherent.hasTelephone %}
                    <a class="fa fa-phone" aria-hidden="true"
                       title="Téléphoner à  {{ adherent.prenom }} {{ adherent.nom }}"
                       href="tel: {{ adherent.telephone }}"></a>
                {% endif %}
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

src/AppBundle/Resources/views/Adherent/Block/menu.html.twig
<ul class="nav nav-pills flex-column">
    {% for element in liste_elements %}
        {% set is_granted = false %}
        {% for role in element.listeRoles %}
            {% if  not is_granted %}
                {% set is_granted = is_granted(role) %}
            {% endif %}
        {% endfor %}
        {% if is_granted %}
            <li  class="nav-item"><a class="nav-link {% if element.route == current_route  %}  active{% endif %}" href="{{ path(element.route) }}">{{ element.name|capitalize }}</a></li>
        {% endif %}
    {% endfor %}
</ul>